# ALM Team Azure example pipeline that pulls in the maven build template from the devops_pipelines repository
# Copy this file to your repository and fill in the required parameters, AppName and Portfolio
# Commit the changes and trigger a new build

trigger:
- master

# Repo: devops_pipelines/templates
# File: azure-pipelines.yml
resources:
  repositories:
    - repository: almtemplates
      type: git
      name: ALM/devops_pipelines

stages:
- stage: Build
  jobs:
  - template: templates/azure-java-mvn.yml@almtemplates
    parameters:
      AppName: 'polyglot-maven'
      Portfolio: 'ESM'
      # Optional Parameters showing the current default value
      #AppVersion: '1.0'
      #RunMavenSonarScan: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/master') }} # This expression will return true if the branch is master. Set to 'false' if a scan is unwanted on the master branch.
      MavenGoal: 'clean deploy -U B'
      #JavaVersion: '11' # Default maven version is 11. Pass in '8' for JDK 8
      #SonarServiceConnection: 'ICS SonarQube Service Connection'
