#!/usr/bin/env zsh

if [[ "$1" == "" ]]; then
    echo "set-version <version>"
    exit 1
fi

export version=$1

sed -E -i '' "s/<version>[^<]+<\/version><!--PROJECT_VERSION-->/<version>$version<\/version><!--PROJECT_VERSION-->/g" ./pom.xml ./*/pom.xml
